### ISSUE TITLE
formatted_dataの仕様書

### ISSUE THREAD

**Issue by yamamoto-ryuzo** [dx-junkyard/OpenData-Library#6]
formatted_dataのデータは外部へ接続点であることは間違いないと思っています。
出来れば、命名のルールを暫定的にでも決めてもらえればシステマチックにその後の作業が可能かと思います。
【ルール例】
　整理番号_merged.csv

【利用例】
例）子育て支援
　OpenData-Library　の成果　[00001_merged.csv]
　リレーションしたい付属データ 00001_relation.csv
　で、付加データを自動的に追加した成果品を生成できます。
例）子育て支援
　ベースとなるデータ 00001_base.csv
　例えば、このベースデータを基本にデータ整理を行い、00001_merged.csvから座標を取、無いものは都道府県市区町村の代表地点に貼り付け
　なども可能です。
そのようなことも標準化していくことで全体として整理してゆくのだという方向性を示すことが長期的に開発するのなら大事かと思います。

データで大事なのはコア情報の標準化
下の部分がいわば標準化！規格化になる非常に重要な属性だと思います。
![image](https://github.com/dx-junkyard/OpenData-Library/assets/86514652/a250b549-de6a-45e8-819a-55079475abef)

**Comment by urashin** [comment]
@yamamoto-ryuzo １つの整理番号対して一つのユースケースで各工程の定義ファイルや入出力ファイルにその整理番号を使った場合、異なるユースケースに転用した場合の管理が逆に煩雑になってしましますので、ファイル名をユニークにする目的で生成順に番号を割り当てますが、番号自体に意味はなく、同じ番号が何らかの共通要素を示すわけでもなく、それがどのような目的で何と関連付けられるのかはpipeline定義で関連付けや確認ができるようにしておくのがよいかもしれません。

**Comment by yamamoto-ryuzo** [comment]
@urashin 
>それがどのような目的で何と関連付けられるのかはpipeline定義で関連付けや確認ができるようにしておくのがよいかもしれません。

　情報量が増えると　OpenData-Library　のメタデータのような感じでいいと思います。

>ファイル名をユニークにする目的で生成順に番号を割り当てます

 　それ！とてもありがたいです。ルールさえ明示してもらえれば、それが複雑だろうが簡単だろうがマシンリーダブルになるのかなと思います。

**Comment by urashin** [comment]
整形済のデータはOpenData-Archiveの方で扱うように整理しました。
フォルダ構成は何で処理をした結果なのかわかるよう、OpenData-Libraryと同じ構成にしておき、使用したLibraryの処理プロセスと同じパスをArchiveにも用意し、そこに整形済のデータを配置してください。

**Comment by yamamoto-ryuzo** [comment]
https://github.com/dx-junkyard/OpenData-Archive
ですね！
了解です。
Archive　＞　Postgres 　＞　PostGREST　+　GIS　でもまったりとやってみます。
いつかどこかのハッカソンで役に立つかも？？？
